[platformio]
build_dir = ~/.pio/build/${PROJECT_HASH}

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_ldf_mode = chain+
lib_ignore =
    ArduinoOTA
    AsyncUDP
    BLE
    BluetoothSerial
    DNSServer
    ESPmDNS
    Ethernet
    FFat
    FS
    HTTPUpdateServer
    I2S
    Insights
    LittleFS
    NetBIOS
    Preferences
    RainMaker
    SD
    SD_MMC
    SimpleBLE
    SPIFFS
    Ticker
    Update
    USB
    WebServer
    WiFiProv